### ISSUE TITLE
`kmeshctl dump` failed

### ISSUE THREAD

**Issue by YaoZengzeng** [kmesh-net/kmesh#1016]
**Task description**:

`kmeshctl dump` failed to execute becasuse rename of Kmesh mode from `ads` & `workload` to `kernel-native` & `dual-engine`

```bash
root@dev:~/kmesh# kmeshctl dump kmesh-ctq7d dual-engine 
404 page not found
```

**Solution**:

The mode in the url should also be updated:

https://github.com/kmesh-net/kmesh/blob/main/pkg/status/status_server.go#L53-L57

friendly ping @codesmith25103 if you're interested :)

***If no one claims this for a while, I will do it myself, because this subcommand is very commonly used in the dev process***

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by Okabe-Rintarou-0** [comment]
@codesmith25103 you can also support dump bpf map, through adding a new flag like `--bpf` :)

**Comment by codesmith25103** [comment]
yeah sure... I am working on it. Thank you @Okabe-Rintarou-0

**Comment by codesmith25103** [comment]
I have free hard disk of only 30 gb right now. Can this be result for "failing for resources"?

**Comment by YaoZengzeng** [comment]
Yes, first check the reason why the pod is in the pending state.

**Comment by codesmith25103** [comment]
I have resolved the issue which i was getting earlier, now after building the kmesh using ```make docker```, i am not able to load that image into my clusture.

**Comment by LiZhenCheng9527** [comment]
> I have resolved the issue which i was getting earlier, now after building the kmesh using `make docker`, i am not able to load that image into my clusture.

Are you able to describe the problem you're experiencing in more detail? 
Is your cluster a `kind` cluster? 
Can't load image. Have you tried the `kind load docker-image <image_name>` command?

**Comment by codesmith25103** [comment]
yes i have made the cluster using kind.  
![image](https://github.com/user-attachments/assets/5dc91fb1-9604-40c0-a836-9a272a6ed9f9)
but even after this step when i am going into nodes i am not finding image in it

**Comment by LiZhenCheng9527** [comment]
why load `kmesh-build`? 
This is the image that provides the compilation env.
And can you provide the result of this commend: `docker exec -it ambient-control-plane crictl image`

**Comment by codesmith25103** [comment]
@LiZhenCheng9527 sorry for mistake. So i have successfully build the image and loaded into kmesh. but on next command ```sankalp@sankalp-HP-Laptop-14s-dq1xxx:~/openSource/kmesh$ kubectl edit ds kmesh -n kmesh-system
Error from server (NotFound): namespaces "kmesh-system" not found``` 
I encounter this error

**Comment by codesmith25103** [comment]
@LiZhenCheng9527 Sorry for mistake. I have build new image  
![image](https://github.com/user-attachments/assets/6b9b6914-fc3e-4f6b-bea7-73a97296a780)

image repository is kmesh and tag is latest with image id  91bef16e249a,  then i have loaded the image using 
```kind load docker-image kmesh:latest --name ambient``` and got the following output 

![image](https://github.com/user-attachments/assets/674e2a14-00e8-41af-aa6a-cfea6c166318)

and after running this command ``` docker exec -it ambient-control-plane crictl image ```

I got following result 

![image](https://github.com/user-attachments/assets/6ca3ba24-a203-4d0d-9cef-964c665b4de4)

**Comment by codesmith25103** [comment]
Thank you @LiZhenCheng9527. I have successfully build the image and load it into the cluster. But as given in the document the next command which ```kubectl edit ds kmesh -n kmesh-system``` which is giving following error ``` Error from server (NotFound): namespaces "kmesh-system" not found ```.

**Comment by codesmith25103** [comment]
Meanwhile when trying to replicate the issue ``` 
sudo kmeshctl dump kmesh-ctq7d dual-engine 
time="2024-11-06T21:43:54+05:30" level=error msg="failed to start port forwarder for Kmesh daemon pod kmesh-ctq7d: failure running port forward process: building port forwarded: failed retrieving: Get \"http://localhost:8080/api/v1/namespaces/kmesh-system/pods/kmesh-ctq7d\": dial tcp 127.0.0.1:8080: connect: connection refused in the \"kmesh-system\" namespace" subsys=kmeshctl/dump
time="2024-11-06T21:43:54+05:30" level=error msg="failed to make HTTP request: Get \"http://localhost:0/debug/config_dump/dual-engine\": dial tcp 127.0.0.1:0: connect: connection refused" subsys=kmeshctl/dump```. I got this

**Comment by LiZhenCheng9527** [comment]
> Thank you @LiZhenCheng9527. I have successfully build the image and load it into the cluster. But as given in the document the next command which `kubectl edit ds kmesh -n kmesh-system` which is giving following error `Error from server (NotFound): namespaces "kmesh-system" not found`. Do i have to create namespace named "kmesh-system"?

Which document are you referring to? You can refer to [this](https://kmesh.net/en/docs/setup/quickstart/) to deploy kmesh.

If you want to build a new image to test, you can run `make docker TAG=1.2.3`.
After you deploy kmesh and load docker image into kind cluster, use `kubectl edit daemonset kmesh -n kmesh-system` change Kmesh image version `latest` to `1.2.3`. Just wait for kmesh pod to finish rebooting.

**Comment by codesmith25103** [comment]
I successfully built the Docker image with the tag 1.2.3, loaded the image, and updated the kmesh version to 1.2.3. I was able to replicate the issue and will now work on resolving it. Thank you, @LiZhenCheng9527.

**Comment by codesmith25103** [comment]
Hey @LiZhenCheng9527 @Okabe-Rintarou-0, just checking—do I need to rebuild the code, load it into the pod, update the Kmesh version in the pod, and rerun it every time I want to test?

**Comment by LiZhenCheng9527** [comment]
> Hey @LiZhenCheng9527 @Okabe-Rintarou-0, just checking—do I need to rebuild the code, load it into the pod, update the Kmesh version in the pod, and rerun it every time I want to test?

You need to rebuild the code and load it into the pod to find the problem. 
If you've identified what's wrong and proceeded to change the function and want to test the function's functionality, you can use go's [ut](https://kmesh.net/en/docs/developer/run-ut/) test for verification.
But if you change the `c` code you can only verify it in the real environment after compiling the image.
The kmesh version is dont need update everytime. If you use `1.2.3` tag, you just need to make sure that your compiled image always has this tag. loading a new image into kind will replace the old one.

**Comment by hzxuzhonghu** [comment]
@codesmith25103 any progress

**Comment by codesmith25103** [comment]
@hzxuzhonghu Yes I am working on it.

**Comment by codesmith25103** [comment]
Hello @YaoZengzeng and @LiZhenCheng9527,

I attempted to resolve the issue by modifying the mode in the URL in [status_server.go](https://github.com/kmesh-net/kmesh/blob/main/pkg/status/status_server.go#L53-L57). Additionally, I explored potential changes that might address the issue, but unfortunately, I have not been successful.

Could you kindly provide some guidance on how I might proceed?

**Comment by LiZhenCheng9527** [comment]
> I attempted to resolve the issue by modifying the mode in the URL in [status_server.go](https://github.com/kmesh-net/kmesh/blob/main/pkg/status/status_server.go#L53-L57). Additionally, I explored potential changes that might address the issue, but unfortunately, I have not been successful.
> 
> Could you kindly provide some guidance on how I might proceed?

so, can you describe your problems?

**Comment by codesmith25103** [comment]
I made the required changes. When I ran the command ```kmeshctl dump kmesh-ctq7d dual-engine```, I received the following result:

![image](https://github.com/user-attachments/assets/1395014d-e81a-42d1-a8f7-cc042f8e45f8)


However on running ```kmeshctl dump kmesh-ctq7d kernel-native```, I am reciving following error 

![image](https://github.com/user-attachments/assets/4c50289b-ef68-4b88-9527-bf8b5f935074)

**Comment by YaoZengzeng** [comment]
> I made the required changes. When I ran the command `kmeshctl dump kmesh-ctq7d dual-engine`, I received the following result:
> 
> ![image](https://private-user-images.githubusercontent.com/102778847/386467315-1395014d-e81a-42d1-a8f7-cc042f8e45f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTE0OTcsIm5iZiI6MTczMTY1MTE5NywicGF0aCI6Ii8xMDI3Nzg4NDcvMzg2NDY3MzE1LTEzOTUwMTRkLWU4MWEtNDJkMS1hOGY3LWNjMDQyZjhlNDVmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwNjEzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzkxNGQ1ZjUxNzIwNjJmZDI4OTA0MjE3NjExZWQ4NDFjYjA3NDE2ZjgzYjBlNGY0ZjFjNGFiNTkwOGQ5MDU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kM1oKtpc2m5fLSFotKwURxojF3bQIrov1e5jKmNPQdM)
> 
> However on running `kmeshctl dump kmesh-ctq7d kernel-native`, I am reciving following error
> 
> ![image](https://private-user-images.githubusercontent.com/102778847/386468437-4c50289b-ef68-4b88-9527-bf8b5f935074.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTE0OTcsIm5iZiI6MTczMTY1MTE5NywicGF0aCI6Ii8xMDI3Nzg4NDcvMzg2NDY4NDM3LTRjNTAyODliLWVmNjgtNGI4OC05NTI3LWJmOGI1ZjkzNTA3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwNjEzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTc0NjZlYmE1ZTMzYmRlM2NmNzRjZWYxOTNhYTNmNmE5OTYxZjcwNTRkMTkwMTA2NDZmMDBmN2VjZjY0MzQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Xombm5pe4Ezz213uq0RTObnEtHDu0ghn_VffyjmBt34)

It's OK, this is the result we want.

**Comment by codesmith25103** [comment]
That's good to know. I have open the PR request which will close this issue.
