### ISSUE TITLE
Auto generate cobra command docs

### ISSUE THREAD

**Issue by Okabe-Rintarou-0** [kmesh-net/kmesh#1020]
**Task description**:
Cobra support generating docs:
https://www.emmanuelgautier.com/blog/snippets/go-cobra-docgen
**Solution**:

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by Okabe-Rintarou-0** [comment]
We can generate docs automatically using this tools, and place them somewhere.

**Comment by hzxuzhonghu** [comment]
what does it look like ? Better have a view from other project

**Comment by Okabe-Rintarou-0** [comment]
> what does it look like ? Better have a view from other project

here's an example:
## mycmd

A brief description of your command

### Synopsis

A more detailed description of what your command does.

```
mycmd [flags]
```

### Options

```
  -h, --help   help for mycmd
```

###### Auto generated by spf13/cobra on 6-Nov-2024

**Comment by hzxuzhonghu** [comment]
make sense to me

**Comment by LiZhenCheng9527** [comment]
https://github.com/kmesh-net/kmesh/pull/1015/files#diff-cf9b921287c2c7ecb0d2c56bb2b24645ac831c76bc1d58c6b1ccfcc0ba37b427

This file is regenerated for each commit. Can it be changed?

**Comment by Okabe-Rintarou-0** [comment]
> https://github.com/kmesh-net/kmesh/pull/1015/files#diff-cf9b921287c2c7ecb0d2c56bb2b24645ac831c76bc1d58c6b1ccfcc0ba37b427
> 
> This file is regenerated for each commit. Can it be changed?

will fix it: https://github.com/spf13/cobra/blob/main/site/content/docgen/_index.md
