### ISSUE TITLE
Improve the compatibility of Kmesh observability with the Istio ecosystem

### ISSUE THREAD

**Issue by delavet** [kmesh-net/kmesh#1033]
**Task description**:
1. Currently, the names of kmesh's observability metrics begin with "kmesh," such as "kmesh_tcp_workload_sent_bytes_total". This could break some software in Istio Ecosystem such as kiali, which shows mesh topology graph based on Istio standard metrics like "istio_tcp_sent_bytes_total"

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by Kuromesi** [comment]
Also, I have noticed that all metrics are stored in a single kmesh controller pod, in my experience, when there are about thousands destination services , memory usage can increase up to about 500 mb for a SINGLE envoy sidecar, so I think maybe we should find out a solution for the cost.

**Comment by hzxuzhonghu** [comment]
cc @LiZhenCheng9527

**Comment by LiZhenCheng9527** [comment]
> /assign

So are you responsible for adapting istio's standard telemetry API?

**Comment by delavet** [comment]
> > /assign
> 
> So are you responsible for adapting istio's standard telemetry API?

I will currently focus on producing documentation that utilizes the Prometheus rename mechanism to make Kiali work on Kmesh. As for adapting the Telemetry API, based on previous discussions, the semantics of the Telemetry API may not be appropriate for the sidecar-less data plane models like Kmesh and ambient. Maybe we can first look at how the Istio community supports this for ambient. Currently, Ztunnel does not support it.

**Comment by LiZhenCheng9527** [comment]
> 
> I will currently focus on producing documentation that utilizes the Prometheus rename mechanism to make Kiali work on Kmesh. As for adapting the Telemetry API, based on previous discussions, the semantics of the Telemetry API may not be appropriate for the sidecar-less data plane models like Kmesh and ambient. Maybe we can first look at how the Istio community supports this for ambient. Currently, Ztunnel does not support it.

Well Done. 
I will focus on improving the kmesh metrics deletion mechanism and scheduled erasing outdataed metrics data.
