### ISSUE TITLE
I数据面用kmesh,控制面用什么呢，支持xds么

### ISSUE THREAD

**Issue by 13567436138** [kmesh-net/kmesh#1058]
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:
I数据面用kmesh,控制面用什么呢，支持xds么
**Environment**:
- Kmesh version:
- Others:

**Comment by hzxuzhonghu** [comment]
Yeah, kmesh can work in two patterns now: kerbel-native and dual-enginee 

Both patterns, it make use of istiod as the control plane. 

For kernel-native, kmesh will subscribe traditional xds (lds,rds,cds,eds).
For dual-enginee, kmesh will subscribe new xds(workload/service, authorization policy, etc)
