### ISSUE TITLE
Add documents on kmesh locality failover features

### ISSUE THREAD

**Issue by hzxuzhonghu** [kmesh-net/kmesh#1061]
**What would you like to be added**:

**Why is this needed**:

**Comment by hzxuzhonghu** [comment]
@derekwin

**Comment by derekwin** [comment]
to this pr: https://github.com/kmesh-net/website/pull/90

**Comment by derekwin** [comment]
The implementation schematic can be viewed here: https://github.com/kmesh-net/kmesh/pull/574

**Comment by hzxuzhonghu** [comment]
done
