### ISSUE TITLE
Installation guide needs update

### ISSUE THREAD

**Issue by kevin-wangzefeng** [kmesh-net/kmesh#1082]
**Task description**:
For [installation guide](https://kmesh.net/en/docs/setup/quickstart/), it would be helpful to include:
- supported kubernetes versions matrix
- supported istio versions matrix as control plan 
- requirements on kernel versions

We also need to rephrase categories at <https://github.com/kmesh-net/kmesh/blob/main/docs/kmesh_support.md>, to reflect the "Dual-Engine Mode" and "Kernel-Native Mode"

**Solution**:

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by sureshkrishnan-v** [comment]
Hi, I’d like to work on this issue as a first-time contributor—could you confirm if it’s available and share any guidelines?

**Comment by LiZhenCheng9527** [comment]
Sorry I'm working on this issues.
Maybe you can focus on #1065.

**Comment by sureshkrishnan-v** [comment]
that's great i will work on that issue you mentioned #1065

**Comment by LiZhenCheng9527** [comment]
Thanks.
/assign
