### ISSUE TITLE
Question about destination_service and destination_service_name metric labels

### ISSUE THREAD

**Issue by delavet** [kmesh-net/kmesh#1089]
**Please provide an in-depth description of the question you have**:
I have found out a strange behavior about the metric labels exported by Kmesh. I'm testing in dual-engine mode. If you explore the tcp traffics and compare the `destination_service` and `destination_service_name` labels, you'll see that these two labels are exactly the same: they are Service FQDN.
![image](https://github.com/user-attachments/assets/7e03d17f-f387-420d-a563-ae264c090fae)

**What do you think about this question?**:
Istio has explained these two metrics in the documentation about Istio Standard Metrics(https://istio.io/latest/docs/reference/config/metrics/).

> Destination Service: This identifies destination service host responsible for an incoming request. Ex: details.default.svc.cluster.local.

> Destination Service Name: This identifies the destination service name. Ex: details.

As for Kmesh, I'm not sure if this is a bug, or this is designed by purpose. Therefore I just submit a question here.

A known effection of this issue is that Kiali may draw Service nodes on its traffic graph depends on the `destination_service_name` label.

**Environment**:
- Kmesh version: latest
- Others:

**Comment by LiZhenCheng9527** [comment]
https://github.com/kmesh-net/kmesh/blob/1fca90737c55adc8392f91ee6cb56de471298e00/pkg/controller/telemetry/metric.go#L424-L449

Changing the code on this side should do the trick.

**Comment by Kuromesi** [comment]
> https://github.com/kmesh-net/kmesh/blob/1fca90737c55adc8392f91ee6cb56de471298e00/pkg/controller/telemetry/metric.go#L424-L449
> 
> Changing the code on this side should do the trick.

I'm wondering if we should also store `serviceCache` in the MetricController, so that we can index services from it?

**Comment by LiZhenCheng9527** [comment]
https://github.com/LiZhenCheng9527/kmesh/blob/1fca90737c55adc8392f91ee6cb56de471298e00/pkg/controller/workload/cache/service_cache.go#L34-L40

In controller.processer there is serviceCacha. Not sure if this will meet for your requests.

**Comment by Kuromesi** [comment]
I'm trying to fix the issue by adding a `serviceCache` in MetricController and index services when buildServiceMetric, I'm not sure is it more reasonable?

```go
type MetricController struct {
	EnableAccesslog     atomic.Bool
	EnableMonitoring    atomic.Bool
	workloadCache       cache.WorkloadCache
        // add service cache
	serviceCache       cache.ServiceCache
	workloadMetricCache map[workloadMetricLabels]*workloadMetricInfo
	serviceMetricCache  map[serviceMetricLabels]*serviceMetricInfo
	mutex               sync.RWMutex
}

// buildServiceMetric
namespacedhost := ""
for k, portList := range dstWorkload.Services {
	for _, port := range portList.Ports {
		if port.TargetPort == uint32(dstPort) {
			namespacedhost = k
			break
		}
	}
	if namespacedhost != "" {
		break
	}
}

svcHost := ""
svcNamespace := ""
if len(strings.Split(namespacedhost, "/")) == 2 {
	svcNamespace = strings.Split(namespacedhost, "/")[0]
	svcHost = strings.Split(namespacedhost, "/")[1]
}

// index service
svc := m.serviceCache.GetService(namespacedhost)
trafficLabels.destinationService = svc.HostName
trafficLabels.destinationServiceNamespace = svcNamespace
trafficLabels.destinationServiceName = svc.Name
```

**Comment by LiZhenCheng9527** [comment]
Yes, that does make more sense.
