### ISSUE TITLE
Why can't I import kmesh's own package?

### ISSUE THREAD

**Issue by LiZhenCheng9527** [kmesh-net/kmesh#109]
**Please provide an in-depth description of the question you have**:
Before I contribute to the kmesh project, I tried to set up the kmesh development environment. When I executed `go mod tidy`, I encountered the following error.
```console
kmesh.net/kmesh/api/v2/endpoint: cannot find module providing package kmesh.net/kmesh/api/v2/endpoint: unrecognized import path "kmesh.net/kmesh/api/v2/endpoint": reading https://kmesh.net/kmesh/api/v2/endpoint?go-get=1: 404 Not Found
```
I tried many methods but none of them could resolve it. Do you have any suggestions on how to solve this?
**What do you think about this question?**:
Maybe there's something I'm not dealing with that's causing this.
**Environment**:
- Kmesh version:0.1.0

**Comment by LiZhenCheng9527** [comment]
If these steps are specifically required by kmesh, I think they should be aligned with other projects or a guidance document should be provided.

**Comment by hzxuzhonghu** [comment]
Yes, first you need to generate protobuf with the patch https://github.com/kmesh-net/kmesh/pull/106
