### ISSUE TITLE
VS and DR have not taken effect

### ISSUE THREAD

**Issue by zgqqiang** [kmesh-net/kmesh#1104]
The xdp hook is normal, but the cgroup_comnect4sprog hook only triggers when adding or removing kmesh, causing the created vs and dr policies to fail to take effect

according to https://kmesh.net/zh/blog/deploy_kmesh_in_asm/ Conducted by

5.15.0-113-generic

PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

I successfully tested the system basic image, but it seems to be an issue with the system basic image. However, the reason is unclear

NAME="Huawei Cloud EulerOS"
VERSION="2.0 (x86_64)"
ID="hce"
VERSION_ID="2.0"
PRETTY_NAME="Huawei Cloud EulerOS 2.0 (x86_64)"
ANSI_COLOR="0;31"

5.10.0-182.0.0.95.r1941_123.hce2.x86_64

**Comment by LiZhenCheng9527** [comment]
@weli-l

**Comment by hzxuzhonghu** [comment]
from your description it has nothing todo with vs and dr, so why do you say they do not work?

**Comment by LiZhenCheng9527** [comment]
Can you provide more logs?

**Comment by zgqqiang** [comment]
@LiZhenCheng9527   What other logs can I print
static inline bool is_control_connect(struct kmesh_context *kmesh_ctx, __u32 ip, __u32 port)
{
    BPF_LOG(ERR, KMESH, "is_control_connect is %d %d\n", bpf_ntohs(kmesh_ctx->ctx->user_port), port);
    if (bpf_ntohs(kmesh_ctx->ctx->user_port) != port)
        return false;
    BPF_LOG(ERR, KMESH, "is_control_connect is %d %d\n", kmesh_ctx->ctx->family, AF_INET);
    BPF_LOG(ERR, KMESH, "is_control_connect is %u %u\n", bpf_ntohl(kmesh_ctx->orig_dst_addr.ip4), ip);
    BPF_LOG(ERR, KMESH, "Protocol is %d\n", kmesh_ctx->ctx->protocol);
    if (kmesh_ctx->ctx->family == AF_INET)
        return (bpf_ntohl(kmesh_ctx->orig_dst_addr.ip4) == ip);

time="2024-12-10T08:54:58Z" level=info msg="[KMESH] ERR: handle_kmesh_manage_process begin\n" subsys=ebpf
time="2024-12-10T08:54:58Z" level=info msg="[KMESH] ERR: is_control_connect is 929 929\n" subsys=ebpf
time="2024-12-10T08:54:58Z" level=info msg="[KMESH] ERR: is_control_connect is 2 2\n" subsys=ebpf
time="2024-12-10T08:54:58Z" level=info msg="[KMESH] ERR: is_control_connect is 2 2\n" subsys=ebpf
time="2024-12-10T08:54:58Z" level=info msg="[KMESH] ERR: Protocol is 6\n" subsys=ebpf

**Comment by LiZhenCheng9527** [comment]
You can use `kubectl logs -n kmesh-system <kmesh-pod-name>` provide kmesh pod logs.
And you can use `kmeshctl log <kmesh-pod-name> --set bpf:debug` enable bpf log debug mode.
If you don't have `kmeshctl`. You can `make kmeshctl` to build it. 
`./kmeshctl log <kmesh-pod-name> --set bpf:debug`

**Comment by zgqqiang** [comment]
root@hcss-ecs-0841:~# kubectl logs -nkmesh-system kmesh-d4thf 
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
time="2024-12-10T09:48:12Z" level=info msg="FLAG: --bpf-fs-path=\"/sys/fs/bpf\"" subsys=manager
time="2024-12-10T09:48:12Z" level=info msg="FLAG: --cgroup2-path=\"/mnt/kmesh_cgroup2\"" subsys=manager
time="2024-12-10T09:48:12Z" level=info msg="FLAG: --cni-etc-path=\"/etc/cni/net.d\"" subsys=manager
time="2024-12-10T09:48:12Z" level=info msg="FLAG: --conflist-name=\"\"" subsys=manager
time="2024-12-10T09:48:12Z" level=info msg="FLAG: --enable-bypass=\"false\"" subsys=manager
time="2024-12-10T09:48:12Z" level=info msg="FLAG: --enable-mda=\"false\"" subsys=manager
time="2024-12-10T09:48:12Z" level=info msg="FLAG: --enable-secret-manager=\"false\"" subsys=manager
time="2024-12-10T09:48:12Z" level=info msg="FLAG: --help=\"false\"" subsys=manager
time="2024-12-10T09:48:12Z" level=info msg="FLAG: --mode=\"dual-engine\"" subsys=manager
time="2024-12-10T09:48:12Z" level=info msg="FLAG: --monitoring=\"true\"" subsys=manager
time="2024-12-10T09:48:12Z" level=info msg="FLAG: --plugin-cni-chained=\"true\"" subsys=manager
time="2024-12-10T09:48:12Z" level=info msg="FLAG: --profiling=\"false\"" subsys=manager
time="2024-12-10T09:48:12Z" level=info msg="kmesh version map loadfailed: no such file or directory, start normally" subsys=bpf
time="2024-12-10T09:48:12Z" level=info msg="kmesh start with Normal" subsys=bpf
time="2024-12-10T09:48:13Z" level=error msg="failed to get node: nodes \"hcss-ecs-0841\" is forbidden: User \"system:serviceaccount:kmesh-system:kmesh\" cannot get resource \"nodes\" in API group \"\" at the cluster scope" subsys=bpf
time="2024-12-10T09:48:13Z" level=info msg="bpf loader start successfully" subsys=manager
time="2024-12-10T09:48:13Z" level=info msg="start kmesh manage controller successfully" subsys=controller
time="2024-12-10T09:48:13Z" level=info msg="proxy ztunnel~172.16.63.217~kmesh-d4thf.kmesh-system~kmesh-system.svc.cluster.local connect to discovery address istiod.istio-system.svc:15012" subsys=controller/config
time="2024-12-10T09:48:13Z" level=info msg="default/fortio-v1-965cbdc67-qpd99: enable Kmesh manage" subsys=manage_controller
time="2024-12-10T09:48:13Z" level=info msg="default/fortio-v2-576c5dd4d5-l2cjx: enable Kmesh manage" subsys=manage_controller
time="2024-12-10T09:48:13Z" level=info msg="default/curl-6c56689f48-rwsqv: enable Kmesh manage" subsys=manage_controller
time="2024-12-10T09:48:13Z" level=info msg="controller start successfully" subsys=manager
time="2024-12-10T09:48:13Z" level=info msg="start write CNI config" subsys="cni installer"
time="2024-12-10T09:48:13Z" level=info msg="kmesh cni use chained\n" subsys="cni installer"
time="2024-12-10T09:48:13Z" level=info msg="reload authz config from last epoch" subsys=workload_controller
time="2024-12-10T09:48:13Z" level=info msg="add annotation for pod default/fortio-v1-965cbdc67-qpd99" subsys=manage_controller
time="2024-12-10T09:48:13Z" level=info msg="add annotation for pod default/fortio-v2-576c5dd4d5-l2cjx" subsys=manage_controller
time="2024-12-10T09:48:13Z" level=info msg="add annotation for pod default/curl-6c56689f48-rwsqv" subsys=manage_controller
time="2024-12-10T09:48:13Z" level=info msg="Copied /usr/bin/kmesh-cni to /opt/cni/bin." subsys="cni installer"
time="2024-12-10T09:48:13Z" level=info msg="wrote kubeconfig file /etc/cni/net.d/kmesh-cni-kubeconfig" subsys="cni installer"
time="2024-12-10T09:48:13Z" level=info msg="cni config file: /etc/cni/net.d/10-calico.conflist" subsys="cni installer"
time="2024-12-10T09:48:13Z" level=info msg="start cni successfully" subsys=manager
time="2024-12-10T09:48:13Z" level=info msg="start watching file /var/run/secrets/kubernetes.io/serviceaccount/token" subsys="cni installer"
@LiZhenCheng9527

**Comment by LiZhenCheng9527** [comment]
```
time="2024-12-10T09:48:13Z" level=info msg="add annotation for pod default/fortio-v1-965cbdc67-qpd99" subsys=manage_controller
time="2024-12-10T09:48:13Z" level=info msg="add annotation for pod default/fortio-v2-576c5dd4d5-l2cjx" subsys=manage_controller
time="2024-12-10T09:48:13Z" level=info msg="add annotation for pod default/curl-6c56689f48-rwsqv" subsys=manage_controller
```
The logs show that these three pods have been managed by kmesh. 
Are you experiencing a problem where you don't see the processing of the pods being managed in the cgroup?

**Comment by zgqqiang** [comment]
Yes, I see that the pod is already managed by kmesh, but the created vs and dr policies have not taken effect. I have also created waypoints using kmeshctl dump worklod, and I can see the corresponding data  @LiZhenCheng9527

**Comment by LiZhenCheng9527** [comment]
So what's your VS and DR setup?
If you want to try out Kmesh's capabilities, you can refer to the [try_request_routing](https://kmesh.net/en/docs/userguide/try_request_routing/)

**Comment by LiZhenCheng9527** [comment]
Can you describe what configuration you used and then what operation you did and what you ended up with?

**Comment by hzxuzhonghu** [comment]
I guess you haven't yet deployed a waypoint, so vs and dr doesnot take effect

**Comment by zgqqiang** [comment]
@hzxuzhonghu @LiZhenCheng9527 I have deployed Waypoint, but now I have found that when curling other pods in the pod, I did not trigger the cgroup_comnect4_mag hook, while the xdp hook was triggered. I am sure that the pod has been managed by kmesh, but I am not sure how this was triggered or what the logic is for this

**Comment by LiZhenCheng9527** [comment]
We need to know by what phenomenon you have come to such a conclusion. According to your procedure we can reproduce the problem. Are you using the configuration refer to [try_request_routing](https://kmesh.net/en/docs/userguide/try_request_routing/) and then it's not taking effect when you access it?

**Comment by zgqqiang** [comment]
@LiZhenCheng9527 https://kmesh.net/en/docs/userguide/try_request_routing/  I configured it according to the document, but it didn't take effect

**Comment by LiZhenCheng9527** [comment]
Than can you tell me is that after you set all the traffic to visit `reviews-v1`, when you go to curl productpage, the traffic doesn't all visit `reviews-v1`? Or another unexpected errors?

**Comment by zgqqiang** [comment]
The traffic is not always on reviews-v1, but randomly on reviews-v1, reviews-v2, and reviews-v3. I'm not sure if Istio only needs to deploy Istio (with the environment variable PILOT-INABLE_SMBIENT=true) @LiZhenCheng9527

**Comment by LiZhenCheng9527** [comment]
Kmesh does not depend on istio cni. What version of istio are you using?
Kmesh `Duel-Engine Mode` need  set `pilot.env.PILOT_ENABLE_AMBIENT=true` in istiod.

**Comment by zgqqiang** [comment]
@LiZhenCheng9527

**Comment by LiZhenCheng9527** [comment]
https://github.com/kmesh-net/kmesh/blob/03dac3818534f9c70f345da985203dc793133827/bpf/kmesh/workload/cgroup_sock.c#L88-L94

Are you not triggering `kmesh_workload_tail_call` here?
You can make sure that `kmesh_ctx.via_waypoint` is true

**Comment by zgqqiang** [comment]
I enable kmesh to trigger HandleKmeshManage, which will call netns.WithNetNSPath -> TriggerControlCommand， Triggering cgroup_comnect4_comg, but the resolved IP is 0.0.0.2, which was directly filtered out in handle_kmesh_manage_comcess. I'm not sure 

![1733902664549](https://github.com/user-attachments/assets/166d6449-e22d-4119-8395-7d23dace9901)
![1733902853022](https://github.com/user-attachments/assets/2fc18bc4-a892-4258-84e2-8c95d1fae035)
![image](https://github.com/user-attachments/assets/195265b3-e72f-4247-9fae-77b3e3687615)

@LiZhenCheng9527

**Comment by LiZhenCheng9527** [comment]
Can you add a wechat to discuss this?

**Comment by zgqqiang** [comment]
@LiZhenCheng9527 13488467429  3ky Or I can add you

**Comment by hzxuzhonghu** [comment]
@zgqqiang Did it work well now

**Comment by zgqqiang** [comment]
@hzxuzhonghu I haven't tested it recently, but after changing the basic image of the system, it works normally. I have asked your engineers @LiZhenCheng9527 and suspect that there is a problem between the pod information managed by the system image and the Cgroup of the Huawei cloud server. The ineffective image was purchased from Huawei Cloud, and the specific reason for this is not given. Has this problem been fixed yet

**Comment by hzxuzhonghu** [comment]
So we can close now
