### ISSUE TITLE
Keep the contents of kmeshBpfConfig during Kmesh restart

### ISSUE THREAD

**Issue by LiZhenCheng9527** [kmesh-net/kmesh#1120]
**What would you like to be added**:
Keep the contents of kmeshBpfConfig unchanged during a Kmesh restart.
**Why is this needed**:
KmeshBpfConfig is now initialised every time Kmesh is restarted. This causes the debug mode for bpf-log to need to be re-enabled each time. So we need to discuss whether we need to keep kmeshBpfConfig unchanged when Kmesh restart.

**Comment by hzxuzhonghu** [comment]
To be clear, do you mean now after each restart kemsh daemon will reset the configuration storred in bpf map?

**Comment by LiZhenCheng9527** [comment]
Yes, it is set to default after every reboot
https://github.com/kmesh-net/kmesh/blob/40aa43f77b6f53624c0624569a14b22eb58af0e4/pkg/bpf/bpf.go#L306-L322
