### ISSUE TITLE
REQUEST: New membership for LiZhenCheng9527

### ISSUE THREAD

**Issue by LiZhenCheng9527** [kmesh-net/kmesh#165]
## GitHub Username
LiZhenCheng9527

## Organization you are requesting membership in
Kmesh

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing group] and [slack]
- [x] I have watched Kmest-net/kmesh on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more Kmesh subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

## Sponsors
@hzxuzhonghu 

## List of contributions to the Kurator project

- PRs reviewed / authored:
  #84
  #90 
  #127 
  #139 
  #142 
  #143 
  #145 
  #147 
  #151 
  #155 
  #162 
  #164 
  #163 

- Issues authored:
  #83 
  #109 
  #126
  #143 
  #157 
  #159
- Issues responded to:
#104 

[community membership guidelines]: https://github.com/kmesh-net/website/blob/main/content/en/docs/community/membership.md
[mailing group]: https://groups.google.com/forum/#!forum/kmesh
[slack]: https://cloud-native.slack.com/archives/C06BU2GB8NL
[watchers list]: https://github.com/kmesh-net/kmesh/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication

**Comment by hzxuzhonghu** [comment]
big +1

**Comment by hzxuzhonghu** [comment]
cc @nlgwcy

**Comment by nlgwcy** [comment]
welcome~ +1

**Comment by hzxuzhonghu** [comment]
invited @LiZhenCheng9527
