### ISSUE TITLE
Compile revision info into binary

### ISSUE THREAD

**Issue by hzxuzhonghu** [kmesh-net/kmesh#198]
**Task description**:

We should compile version,commit hash, and build date into kmesh binary during build. And add version subcommand to allow printing that out. 

So it can help developers to know whether they have tested the expected patch. 

```
# kmesh-daemon version
......
```

This is like `kubectl version`

**Solution**:

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by Okabe-Rintarou-0** [comment]
Does version here mean kmesh version? How can I get it? Can we pass this parameter using environment variables in:

https://github.com/kmesh-net/kmesh/blob/809e92140eb591f4ed5def368d6fc7b5881aeb65/Makefile#L80-L81

**Comment by hzxuzhonghu** [comment]
Right, we can pass from here.. FYI https://github.com/kurator-dev/kurator/blame/main/Makefile#L16

**Comment by Okabe-Rintarou-0** [comment]
> Right, we can pass from here.. FYI https://github.com/kurator-dev/kurator/blame/main/Makefile#L16

thanks！

**Comment by hzxuzhonghu** [comment]
Done
