### ISSUE TITLE
support multi-platform images

### ISSUE THREAD

**Issue by YaoZengzeng** [kmesh-net/kmesh#239]
**What would you like to be added**:

kmesh related images should not have 'arch' suffix, ref: https://github.com/kmesh-net/kmesh/blob/main/kmesh_compile.sh#L22

**Why is this needed**:

docker already support building multi-platform images, ref: https://docs.docker.com/build/building/multi-platform/

**Comment by YaoZengzeng** [comment]
@lec-bit is this issue fixed?

**Comment by LiZhenCheng9527** [comment]
done
/close
