### ISSUE TITLE
`make clean` doesn't clean up completely

### ISSUE THREAD

**Issue by YaoZengzeng** [kmesh-net/kmesh#264]
**What happened**:

After `make docker`, kmesh would produce the following intermediate modifications:

```bash
root@istio-proxy-build-tools-x86:~/yzz/kmesh# git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   bpf/kmesh/bpf2go/bpf2go.go
        modified:   bpf/kmesh/include/config.h
        modified:   config/kmesh_marcos_def.h
        modified:   mk/api-v2-c.pc
        modified:   mk/bpf.pc

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        config/linux-bpf.h

no changes added to commit (use "git add" and/or "git commit -a")
```

And `make clean` will indeed roll back a lot of changes but there are still some omissions:

```
root@istio-proxy-build-tools-x86:~/yzz/kmesh# make clean
git checkout bpf/kmesh/bpf2go/bpf2go.go config/kmesh_marcos_def.h mk/api-v2-c.pc mk/bpf.pc
   CLEAN   kmesh-daemon
   CLEAN   mdacore
   CLEAN   kmesh-cni
   CLEAN   libkmesh_api_v2_c.so
   CLEAN   libkmesh_deserial.so
   CLEAN   kernel
make[1]: Nothing to be done for 'clean'.
root@istio-proxy-build-tools-x86:~/yzz/kmesh# git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   bpf/kmesh/include/config.h

no changes added to commit (use "git add" and/or "git commit -a")
root@istio-proxy-build-tools-x86:~/yzz/kmesh# git diff
diff --git a/bpf/kmesh/include/config.h b/bpf/kmesh/include/config.h
index 4faf4a3..bfed72f 100644
--- a/bpf/kmesh/include/config.h
+++ b/bpf/kmesh/include/config.h
@@ -89,7 +89,7 @@
 #define KMESH_PER_FILTER_NUM             MAP_SIZE_OF_PER_FILTER
 #define KMESH_PER_VIRT_HOST_NUM           MAP_SIZE_OF_PER_VIRTUAL_HOST
 #define KMESH_PER_ROUTE_NUM               MAP_SIZE_OF_PER_ROUTE
-#define KMESH_PER_ENDPOINT_NUM         MAP_SIZE_OF_PER_ENDPOINT
+#define KMESH_PER_ENDPOINT_NUM 15
 #define KMESH_PER_HEADER_MUM 32
 #define KMESH_PER_WEIGHT_CLUSTER_NUM 32
 #endif // _CONFIG_H_
```

**What you expected to happen**:

`make clean` can roll back all changes

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kmesh version: v0.3.0
- Others:

**Comment by Okabe-Rintarou-0** [comment]
It is modified due to the code here:
https://github.com/kmesh-net/kmesh/blob/1ae49ce4b623bc888ad2386d9acbc531d6c62d67/kmesh_compile_env_pre.sh#L37-L42

maybe we can recover it to #define KMESH_PER_ENDPOINT_NUM       MAP_SIZE_OF_PER_ENDPOINT or just git restore it?

**Comment by LiZhenCheng9527** [comment]
I think there is a risk in using git restore, either to abort changes or to RESET. It's better to use the other option.

**Comment by lec-bit** [comment]
When we first built the kmesh compilation capability, in order to adapt to different versions of the kernel and different compilation environments, there were some actions to modify files in the compilation script. These file modifications recorded some information about the current compilation environment.
        modified:   bpf/kmesh/bpf2go/bpf2go.go
        modified:   bpf/kmesh/include/config.h
        modified:   config/kmesh_marcos_def.h

This part of the modification will not have any actual impact on the next compilation. Of course, if it affects the development experience, I think we can use a script to modify this part of the modification.
It can be executed automatically after make docker ends, or when make clean

**Comment by nlgwcy** [comment]
> When we first built the kmesh compilation capability, in order to adapt to different versions of the kernel and different compilation environments, there were some actions to modify files in the compilation script. These file modifications recorded some information about the current compilation environment. modified: bpf/kmesh/bpf2go/bpf2go.go modified: bpf/kmesh/include/config.h modified: config/kmesh_marcos_def.h
> 
> This part of the modification will not have any actual impact on the next compilation. Of course, if it affects the development experience, I think we can use a script to modify this part of the modification. It can be executed automatically after make docker ends, or when make clean

cc @Okabe-Rintarou-0
