### ISSUE TITLE
Unexpected running into auth cleanup when accessing a service uncharged by kmesh

### ISSUE THREAD

**Issue by hzxuzhonghu** [kmesh-net/kmesh#265]
When I startup kmesh in workload mode, and make a request from a pod (managed by kmesh) to a service which is uncharged by kmesh. I can see unexpected bpf trace log.

The cause is that 

bpf/kmesh/workload/sockops_tuple.c#L204~L209 we always call cleanup when a connection close
```
		case BPF_SOCK_OPS_STATE_CB:
			if(skops->args[1] == BPF_TCP_CLOSE || skops->args[1] == BPF_TCP_CLOSE_WAIT 
			|| skops->args[1] == BPF_TCP_FIN_WAIT1)
				clean_auth_map(skops);
				clean_dstinfo_map(skops);
```

**Comment by hzxuzhonghu** [comment]
cc @supercharge-xsy @tacslon

**Comment by hzxuzhonghu** [comment]
Currently it is expected because we cleanup map_of_auth when connection close depending on socket state change, and in CB we cannot know whether  it is src/dst.

But it doesnot matter, calling delete of a none existing key on map have no bad effect

**Comment by nlgwcy** [comment]
The code has processed `-ENOENT`, I think the issue can be closed.
