### ISSUE TITLE
frontend data structure adjustment in the kmesh workload mode

### ISSUE THREAD

**Issue by kwb0523** [kmesh-net/kmesh#277]
**What would you like to be added**:
1.the name of service_id variable in frontend value has limitations and needs to be renamed;
2.the port variable in the frontend key seems to be redundant and needs to be removed;
3.docs of workload mode need to be refreshed.
Plan to handle the above issues in three separate PR
**Why is this needed**:

**Comment by kwb0523** [comment]
kind/enhancement

**Comment by hzxuzhonghu** [comment]
Whyd does not we need ``
