### ISSUE TITLE
pod is not manged in oe23.03

### ISSUE THREAD

**Issue by supercharge-xsy** [kmesh-net/kmesh#298]
**What happened**:
In the oe2303 environment, a pod is deployed in a namespace with kmesh enabled, but it does not seem to be managed.
`[root@localhost helm]# bpftool prog trace | grep 402781194
           <...>-167491  [004] d..21 95722.264353: bpf_trace_printk: [KMESH] DEBUG: origin addr=[402781194:20480]
           <...>-167491  [004] d..21 95722.264356: bpf_trace_printk: [KMESH] DEBUG: bpf find frontend addr=[402781194:20480]
           <...>-167491  [004] d.s41 95722.264471: bpf_trace_printk: [SOCKOPS] INFO: test123 not managed by kmesh, ip:402781194
           <...>-167491  [004] d.s41 95722.264479: bpf_trace_printk: [SOCKOPS] INFO: test123 not managed by kmesh, ip:402781194
`
check kemsh_manage map，only cookie records，without ip records
![image](https://github.com/kmesh-net/kmesh/assets/63693283/69a00598-296e-42e5-bd15-ec92c2fbb3a8)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kmesh version:v0.3.0
- Others:

**Comment by supercharge-xsy** [comment]
@bitcoffeeiux

**Comment by hzxuzhonghu** [comment]
How could two kmesh_manage created?

**Comment by hzxuzhonghu** [comment]
Not sure if this is related to recent fix

```
int record_tuple(struct bpf_sock_ops *skops)
{
    if (skops->family != AF_INET && !ipv4_mapped_addr(skops->local_ip6))
        return 0;
```

**Comment by supercharge-xsy** [comment]
> How could two kmesh_manage created?

Because it's kind mode, I'm querying this on the host machine. there are two kind node with kmesh，so have two map

**Comment by supercharge-xsy** [comment]
> Not sure if this is related to recent fix
> 
> ```
> int record_tuple(struct bpf_sock_ops *skops)
> {
>     if (skops->family != AF_INET && !ipv4_mapped_addr(skops->local_ip6))
>         return 0;
> ```
it is suspected that the problem is caused by this reason. The 2303 has a special judgment.
`
static inline bool conn_from_cni_sim_add(struct bpf_sock_ops *skops)
{
    // cni sim connect 0.0.0.1:929(0x3a1)
    // 0x3a1 is the specific port handled by the cni for enable Kmesh
#if !OE_23_03
    return ((bpf_ntohl(skops->remote_ip4) == 1) && (bpf_ntohl(skops->remote_port) == 0x3a1));
#else
    return ((bpf_ntohl(skops->remote_ip4) == 1) && (bpf_ntohl(skops->remote_port) == 0xa1030000));
#endif
}`
