### ISSUE TITLE
Setting the size of bpf maps in Kmesh

### ISSUE THREAD

**Issue by LiZhenCheng9527** [kmesh-net/kmesh#318]
**What would you like to be added**:
In Kmesh, we declare a number of bpf maps and set their size. However, the previous settings were very confusing and the sizes did not reasonably.
https://github.com/kmesh-net/kmesh/blob/80e02615c1697e7e9416a1c32dd277389ccae02e/bpf/kmesh/include/config.h#L40-L48
We need to discuss the size of the bpf maps according to the actual usage story. Make the size setting more reasonable
**Why is this needed**:

**Comment by LiZhenCheng9527** [comment]
We can discuss this at the next community meeting

**Comment by hzxuzhonghu** [comment]
And for worklaod mode, most are two small, while MAP_SIZE_OF_AUTH  maybe too big

```
#define MAP_SIZE_OF_FRONTEND 100
#define MAP_SIZE_OF_SERVICE  100
#define MAP_SIZE_OF_ENDPOINT 1000
#define MAP_SIZE_OF_BACKEND  500
#define MAP_SIZE_OF_AUTH     8192
#define MAP_SIZE_OF_MANAGER  8192
#define MAP_SIZE_OF_DSTINFO  8192
```

**Comment by LiZhenCheng9527** [comment]
total service mesh：
services 5000
workloads100000
