### ISSUE TITLE
Support waypoint capture mode

### ISSUE THREAD

**Issue by hzxuzhonghu** [kmesh-net/kmesh#321]
**What would you like to be added**:

From istio 1.22, it has supported waypoint capture for service, pod, besides namespace,  https://github.com/istio/istio/issues/49032

Basically it inroduced a new annotation ` istio.io/use-waypoint: [{namespace}/]{gateway-name}`

 we should check what is missing in kmesh, we may not need to do some change in kmesh.  And provide user guide in kmesh

**Comment by hzxuzhonghu** [comment]
We donot need to change our kmesh daemon or waypoint, jusyt need to update https://kmesh.net/en/docs/userguide/try_waypoint/

**Comment by YaoZengzeng** [comment]
Kmesh could support new waypoint capture mode, at different granularity, with any code change.

All needed is doc update. 🚀
