### ISSUE TITLE
Kmesh 具体是哪部分代码实现了流量控制的（比如控制多少百分比）？

### ISSUE THREAD

**Issue by Okabe-Rintarou-0** [kmesh-net/kmesh#349]
Kmesh 具体是哪部分代码实现了流量控制的（比如控制多少百分比）？我阅读了很多代码，但是对于这一块不是很了解，希望能够得到解答。此外，kmesh-controller 会订阅 istiod 的 ads stream，是不是会根据stream里的事件去更新 bpf 里面的各种 workload map，然后在 bpf 做流量管理的时候，会利用到这些map？比如kmesh_service, kmesh_backend之类的？如果有人能解答我的疑惑，我将不胜感激！

**Comment by hzxuzhonghu** [comment]
Currently it is split in route_config.h according to the weight setting in the router configuration

**Comment by Okabe-Rintarou-0** [comment]
> Currently it is split in route_config.h according to the weight setting in the router configuration

Thank you for your reply.
