### ISSUE TITLE
kmesh-cni and kmesh-cni-kubeconfig remove failed when uninstall kmesh

### ISSUE THREAD

**Issue by bfforever** [kmesh-net/kmesh#365]
**What happened**:
when uninstall kmesh, it can not remove kmesh cni and kmesh-cni-kubeconfig correctly.

It report an error `level=error msg="err:remove /opt/cni/bin/kmesh-cni-kubeconfig: no such file or directory, remove CNI config failed, please remove manual" subsys="cni installer"`

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kmesh version:
- Others:

**Comment by hzxuzhonghu** [comment]
can you separate the bug fix from #364
