### ISSUE TITLE
Implement a unified handling logic for remote_port

### ISSUE THREAD

**Issue by nlgwcy** [kmesh-net/kmesh#374]
**What would you like to be added**:
Due to the [modifications ](https://gitee.com/src-openeuler/kernel/blob/b27edc7373b596fc1b85a239ecbfe8dd8722f83c/0010-net-bpf-Sockops-supports-modification-of-remote_ip-a.patch)in oe 23.03, skops->remote_port is inconsistent with other OS versions. Additionally, there are no further update releases for version 23.03, making it impossible to update. The kmesh code needs to handle this field differently depending on whether it is in the oe 23.03 environment or not.

Taking port 15019 as an example, the local sequence is 0x3aab, which corresponds to the network sequence: 0xab3a0000. However, in oe 23.03, it is represented as 0x0000ab3a.

Currently, this handling is scattered throughout various parts of the kmesh code, and it is desired to have a unified approach to handle it.
**Why is this needed**:
Implement a unified handling logic.

**Comment by LiZhenCheng9527** [comment]
Is the result of our last discussion going to be continued support for oe23.03?
