### ISSUE TITLE
Make build very slow

### ISSUE THREAD

**Issue by Okabe-Rintarou-0** [kmesh-net/kmesh#408]
**Please provide an in-depth description of the question you have**:
Make build very slow
![image](https://github.com/kmesh-net/kmesh/assets/58595459/6a224383-da78-4c35-801c-a9a154a559c6)
**What do you think about this question?**:

**Environment**:
Ubuntu 22.04

**Comment by hzxuzhonghu** [comment]
what is it doing, since https://github.com/kmesh-net/kmesh/pull/382 it is much quicker for me

**Comment by Okabe-Rintarou-0** [comment]
![image](https://github.com/kmesh-net/kmesh/assets/58595459/67255f1f-b369-4afa-ba60-a4380ba8f08e)
each item takes a long time, is it due to network problem?

**Comment by LiZhenCheng9527** [comment]
The 0.0B/s in the graph should be the result of the slow network rate.
Perhaps you could `docker pull ghcr.io/kmesh-net/kmesh-build-x86:latest`. Once the image has been downloaded, then try to compile Kmesh

**Comment by Okabe-Rintarou-0** [comment]
> docker pull ghcr.io/kmesh-net/kmesh-build-x86:latest

Already pulled：
root@test:~/kmesh# docker pull ghcr.io/kmesh-net/kmesh-build-x86:latest
latest: Pulling from kmesh-net/kmesh-build-x86
Digest: sha256:0274dfb7dee34054bc3ca15c6842dc2d34dbec57252823043ffd9709020a8052
Status: Image is up to date for ghcr.io/kmesh-net/kmesh-build-x86:latest
ghcr.io/kmesh-net/kmesh-build-x86:latest

**Comment by Okabe-Rintarou-0** [comment]
Seems to be stuck here:

```
root@test:~/kmesh# bash -x ./kmesh_compile.sh 
+ prepare
+ local arch
++ get_arch
+++ arch
++ '[' x86_64 == x86_64 ']'
++ echo x86
+ arch=x86
+ docker pull ghcr.io/kmesh-net/kmesh-build-x86:latest
latest: Pulling from kmesh-net/kmesh-build-x86
Digest: sha256:0274dfb7dee34054bc3ca15c6842dc2d34dbec57252823043ffd9709020a8052
Status: Image is up to date for ghcr.io/kmesh-net/kmesh-build-x86:latest
ghcr.io/kmesh-net/kmesh-build-x86:latest
++ run_docker_container
++ local arch
+++ get_arch
++++ arch
+++ '[' x86_64 == x86_64 ']'
+++ echo x86
++ arch=x86
++ local container_id
++++ pwd
++++ go env GOCACHE
++++ go env GOMODCACHE
+++ docker run -itd --privileged=true -v /usr/src:/usr/src -v /usr/include/linux/bpf.h:/kmesh/config/linux-bpf.h -v /etc/cni/net.d:/etc/cni/net.d -v /opt/cni/bin:/opt/cni/bin -v /mnt:/mnt -v /sys/fs/bpf:/sys/fs/bpf -v /lib/modules:/lib/modules -v /root/kmesh:/kmesh -v /root/.cache/go-build:/root/.cache/go-build -v /root/go/pkg/mod:/go/pkg/mod --name kmesh-build ghcr.io/kmesh-net/kmesh-build-x86:latest
++ container_id=d42d2a1e85198f07988ca0d3dbd8b930a791f515367aceb4b2a820ccf809fed5
++ echo d42d2a1e85198f07988ca0d3dbd8b930a791f515367aceb4b2a820ccf809fed5
+ container_id=d42d2a1e85198f07988ca0d3dbd8b930a791f515367aceb4b2a820ccf809fed5
+ build_kmesh d42d2a1e85198f07988ca0d3dbd8b930a791f515367aceb4b2a820ccf809fed5
+ local container_id=d42d2a1e85198f07988ca0d3dbd8b930a791f515367aceb4b2a820ccf809fed5
+ docker exec d42d2a1e85198f07988ca0d3dbd8b930a791f515367aceb4b2a820ccf809fed5 git config --global --add safe.directory /kmesh
+ docker exec d42d2a1e85198f07988ca0d3dbd8b930a791f515367aceb4b2a820ccf809fed5 sh /kmesh/build.sh
```

**Comment by Okabe-Rintarou-0** [comment]
directly run build.sh is fast

**Comment by LiZhenCheng9527** [comment]
This is unrelated to the kernel version. I'm also running Ubuntu 22.04.

**Comment by Okabe-Rintarou-0** [comment]
Stuck here
![image](https://github.com/kmesh-net/kmesh/assets/58595459/9b5b3af6-69c1-4b14-8f6c-0c7bce230e7f)

**Comment by hzxuzhonghu** [comment]
Seems your network is slow, maybe try using make docker

**Comment by LiZhenCheng9527** [comment]
![image](https://github.com/kmesh-net/kmesh/assets/140870529/61523e36-bc95-4d04-8621-1c218874db75)
Install dependency pkg. 
If you're ubuntu, why isn't it installed use apt.

**Comment by Okabe-Rintarou-0** [comment]
> ![image](https://private-user-images.githubusercontent.com/140870529/335926666-61523e36-bc95-4d04-8621-1c218874db75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODQ0MTMsIm5iZiI6MTcxNzM4NDExMywicGF0aCI6Ii8xNDA4NzA1MjkvMzM1OTI2NjY2LTYxNTIzZTM2LWJjOTUtNGQwNC04NjIxLTFjMjE4ODc0ZGI3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QwMzA4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTA3MWM5NzQ5NTEwN2E0ZGQ0ZDI4NTczNWVkNTc2MjAxMWJiNTlkYTMzYTRmMDE2MTViZGMwM2VhZGU3ZGY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N6duX0WjFenvyxAB6w_IvwPsqvNv1EDQ3vERBo88PiE) Install dependency pkg. If you're ubuntu, why isn't it installed use apt.

It's in kmesh-build docker.

**Comment by bfforever** [comment]
maybe could try add one line before yum install package?  which is 
`sed -i 's#http://repo.openeuler.org#https://mirrors.tuna.tsinghua.edu.cn/openeuler#g' /etc/yum.repos.d/openEuler.repo`

**Comment by Okabe-Rintarou-0** [comment]
It's network problem. Seems that inside container i cannot access internet, wired.

**Comment by Okabe-Rintarou-0** [comment]
Problem solved, it's because the nic mtu not compatible with docker: https://www.zeng.dev/post/2022-the-docker-mtu-problem/
