### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Okabe-Rintarou-0** [kmesh-net/kmesh#452]
**What happened**:
In the current main branch, make build will fail
```
/kmesh/bpf/kmesh/workload/sendmsg.c:115:78: note: passing argument to parameter 'data' here
static inline void sk_msg_write_buf(struct sk_msg_md *msg, __u32 *off, __u8 *data, __u32 len)
                                                                             ^
../workload/sendmsg.c:123:5: error: A call to built-in function 'memcpy' is not supported.
    bpf_memcpy(begin, data, len);
    ^
3 warnings and 1 error generated.
Error: can't execute clang: exit status 1
exit status 1
bpf/kmesh/bpf2go/bpf2go.go:14: running "go": exit status 1
make: *** [Makefile:83: all] Error 1
   INSTALL //usr/lib64/libkmesh_api_v2_c.so
   INSTALL //usr/lib64/libkmesh_deserial.so
make[1]: Nothing to be done for 'install'.
   INSTALL //usr/bin/kmesh-daemon
install: cannot stat 'kmesh-daemon': No such file or directory
make: *** [Makefile:122: install] Error 1
```
**What you expected to happen**:
Should build success
**How to reproduce it (as minimally and precisely as possible)**:
make build
**Anything else we need to know?**:

**Environment**:
- Kmesh version:
- Others:

**Comment by hzxuzhonghu** [comment]
@nlgwcy I can build successfully via ./build.sh, but cannot via `make build`

**Comment by nlgwcy** [comment]
What is os version? I can compile successfully via `make build` in openEuler 22.03 LTS SP3.

**Comment by Okabe-Rintarou-0** [comment]
ubuntu 20.04, github action also failed
![image](https://github.com/kmesh-net/kmesh/assets/58595459/b93a7a88-20f7-4a67-9dba-c61f82a86511)

**Comment by Okabe-Rintarou-0** [comment]
ubuntu 22.04 also failed.

**Comment by hzxuzhonghu** [comment]
I suspect the build image we used does not support memcpy

**Comment by Okabe-Rintarou-0** [comment]
![image](https://github.com/kmesh-net/kmesh/assets/58595459/6519d06b-39c3-4f6a-918a-0c6801ae7867)

**Comment by bfforever** [comment]
`bpf_memcpy(begin, data, len)` change variable len to constant can compile. It seems problem that len is not constant.

**Comment by hzxuzhonghu** [comment]
Why can it build sucessfully with ./build.sh
