### ISSUE TITLE
Merge `/debug/bpfLogLevel/` into `/debug/loggers`

### ISSUE THREAD

**Issue by hzxuzhonghu** [kmesh-net/kmesh#498]
**What would you like to be added**:

This feature has not been released, we can and should do this merge. 

cc @Okabe-Rintarou-0

**Comment by Okabe-Rintarou-0** [comment]
what about use a special logger name like "bpf". 

```shell
kmesh-daemon --set bpf:info
```

**Comment by hzxuzhonghu** [comment]
looks good to me
