### ISSUE TITLE
Which iso to download if I want to create a vm in vmware to use enhanced kernel

### ISSUE THREAD

**Issue by Okabe-Rintarou-0** [kmesh-net/kmesh#525]
**Please provide an in-depth description of the question you have**:
Document kmesh-support.md only gives the url
https://github.com/kmesh-net/kmesh/blob/2e29e86e4064c45fb48fac5e3bc693409ed91734/docs/kmesh_support.md?plain=1#L2-L8

but i am quite confused about which iso should i use. I need the one with enhanced kernel headers.

I tried a version of openeuler 23.03, but it does not contain linux headers.

btw, the document here is not clear enough. Once i have built the env, i'd like to optimize it or add a new one.

![image](https://github.com/kmesh-net/kmesh/assets/58595459/e54e0531-fd90-41eb-9cf5-967e9eb690e3)

**What do you think about this question?**:

**Environment**:
- Kmesh version: current main branch
- Others:

**Comment by bfforever** [comment]
Had try to execute below commands?
```
yum install  kernel-headers
yum install "kernel-devel-uname-r == $(uname -r)"
```

**Comment by Okabe-Rintarou-0** [comment]
yes, that's right.

**Comment by Okabe-Rintarou-0** [comment]
wrote some notes in case someone want to take reference： https://okabe-rintarou-0.github.io/2024/07/09/kmesh-env/
