### ISSUE TITLE
bypass UT is not running stable

### ISSUE THREAD

**Issue by LiZhenCheng9527** [kmesh-net/kmesh#539]
**What would you like to be added**:
Because bypass UT  is not running stable，affects PR submissions. 
I've encountered this several times,
![image](https://github.com/kmesh-net/kmesh/assets/140870529/0f1bd8cd-aa55-445f-bb29-9c70d37fd045)
and running CI again without changing the code gives me different results.
I think the stability of the bypass CI operation should be enhanced.
**Why is this needed**:

**Comment by hzxuzhonghu** [comment]
https://github.com/kmesh-net/kmesh/pull/540 can fix it
