### ISSUE TITLE
curl 127.0.0.1:15200/debug/bpf/ads will Cause Kmesh panic

### ISSUE THREAD

**Issue by PerforMance308** [kmesh-net/kmesh#550]
**What happened**:
![image](https://github.com/kmesh-net/kmesh/assets/12728232/806af165-667f-43b5-900b-47b6143035b3)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kmesh version:
- Others:

**Comment by lec-bit** [comment]
I tried it and it's not stable to reproduce. Can you describe in more detail what you did when you encountered this problem?

**Comment by hzxuzhonghu** [comment]
Please provide `Kmesh version:`, we have fixed a bug on dump panic, not sure if you used a older version

**Comment by hzxuzhonghu** [comment]
https://github.com/kmesh-net/kmesh/issues/348

**Comment by PerforMance308** [comment]
I was using the latest kmesh, built from main at some point last week

**Comment by hzxuzhonghu** [comment]
Please provide more info and better to reproduce

**Comment by hzxuzhonghu** [comment]
Should be fixed by #350
