### ISSUE TITLE
What about adding a document for using enhanced kmesh kernel from scratch?

### ISSUE THREAD

**Issue by Okabe-Rintarou-0** [kmesh-net/kmesh#563]
**Task description**:
I recently deploy a vm with openEuler 23.03 using vmware, i can add some documents for how to deploying it.
**Solution**:

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by Okabe-Rintarou-0** [comment]
This would be one part of #546

**Comment by hzxuzhonghu** [comment]
@lec-bit Could provide some guidance
