### ISSUE TITLE
Pod management can not be canceled

### ISSUE THREAD

**Issue by weli-l** [kmesh-net/kmesh#568]
**What happened**:
after I manage traffic in pod level, management can not be canceled
**What you expected to happen**:
management should be canceled
**How to reproduce it (as minimally and precisely as possible)**:
kubectl label pod xxx istio.io/dataplane-mode=kmesh
kubectl label pod xxx istio.io/dataplane-mode-
**Anything else we need to know?**:

**Environment**:
- Kmesh version:
- Others:

**Comment by hzxuzhonghu** [comment]
can you elaborate a little bit more

**Comment by hzxuzhonghu** [comment]
Understood

**Comment by hzxuzhonghu** [comment]
Fixed
