### ISSUE TITLE
What about extract hashName to a separate package

### ISSUE THREAD

**Issue by Okabe-Rintarou-0** [kmesh-net/kmesh#578]
**Please provide an in-depth description of the question you have**:
Now hashName is in workload controller:
https://github.com/kmesh-net/kmesh/blob/167a806728230ee5a034fc27db956ab227d3a6c5/pkg/controller/workload/workload_hash.go#L36-L56

In my pr for circuitbreaker #570 , I may need to map cluster name to cluster id to meet the requirement of ebpf stack size limit.
![image](https://github.com/user-attachments/assets/6b5798e0-42f9-4823-a8ec-0f2318a57b4c)

**What do you think about this question?**:

**Environment**:
- Kmesh version:
- Others:

**Comment by YaoZengzeng** [comment]
Maybe put into `pkg/utils` is great :)
