### ISSUE TITLE
Remove arch prefix in `/hack/utils.sh`

### ISSUE THREAD

**Issue by Okabe-Rintarou-0** [kmesh-net/kmesh#583]
**Task description**:
https://github.com/kmesh-net/kmesh/blob/01e9c9d9735207f9ffbfbb3f36057008388afe93/hack/utils.sh#L9-L36

Remove arch prefix in `/hack/utils.sh`. Since we are already platform independent.
**Solution**:

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by LiZhenCheng9527** [comment]
I was under the impression that the makefile also had `arch`.
Maybe you can delete it together.

**Comment by Okabe-Rintarou-0** [comment]
> I was under the impression that the makefile also had `arch`. Maybe you can delete it together.

sure
