### ISSUE TITLE
Is kmesh has a slack or discord community channel 

### ISSUE THREAD

**Issue by Patrick0308** [kmesh-net/kmesh#584]
**Please provide an in-depth description of the question you have**:
Is kmesh has a slack or discord community channel?

**What do you think about this question?**:

**Environment**:
- Kmesh version:
- Others:

**Comment by Patrick0308** [comment]
Sorry, I found slack on readme.

**Comment by hzxuzhonghu** [comment]
we have a wechat group, if you are intrested

**Comment by Patrick0308** [comment]
> we have a wechat group, if you are intrested

Yeah, I am

**Comment by Patrick0308** [comment]
@hzxuzhonghu How to join the Wechat group?

**Comment by hzxuzhonghu** [comment]
![mmqrcode1721294728830.png](https://github.com/user-attachments/assets/208fd156-4c8f-4dcd-b676-8aa473fd155b)
