### ISSUE TITLE
XDP prog fails to update

### ISSUE THREAD

**Issue by tacslon** [kmesh-net/kmesh#591]
**What happened**:
Update scenario, when restart kmesh, `XDP` prog is not updated unless restart  managed pods with `kubectl delete -f` and `kubectl apply -f`
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
`helm uninstall`, then `helm install` a newer `kmesh` which `XDP` prog is modified
**Anything else we need to know?**:

**Environment**:
- Kmesh version:
- Others:

**Comment by hzxuzhonghu** [comment]
how do you restart kmesh? Please provide how to reproduce

**Comment by hzxuzhonghu** [comment]
@lec-bit is working on some stuff on restart

**Comment by hzxuzhonghu** [comment]
@tacslon  yesterday, we discussed about this online.  Simliar issue https://github.com/kmesh-net/kmesh/issues/665
