### ISSUE TITLE
We canot assume workload ip address are unique

### ISSUE THREAD

**Issue by hzxuzhonghu** [kmesh-net/kmesh#631]
Since istio is supporting accessing service with hostnetwork pods. It can build workload with hostnetwork with same ip now.  In kmesh we need to adapt to hostnetwork pods.

I haven't looked into what will happend if we kmesh do no change.  Want to hear more voices first.

**Comment by hzxuzhonghu** [comment]
After this commit https://github.com/istio/istio/commit/23852d132a09eb16d03ae246ce1bd45dac60a297, istiod will push workload with hostnetwork set. So we can see workloads with duplicate node ip by calling `/debug/config_dump/workload`

**Comment by hzxuzhonghu** [comment]
Some limitations: 

- authz, we do using src ip to get the source workload, if the source ip is the node ip and shared by many pods, We cannot know which pod it is.
- since the dst hostnetwork is not managed by kmesh, we won't have trouble find the dst workload by ip
- metric builder: we need to find source/dst workload by sock address.  If the ip is shared, we may not be able to find the right workload.
- kmesh_frontend map stores workloadIP->backend uid, if the workloadIP is a shared

**Comment by Okabe-Rintarou-0** [comment]
OK，i can conduct on it。

**Comment by hzxuzhonghu** [comment]
Let me first describe what we can do with hostnetwork pod.

1. Access via a service with hostnetwork pods
2. Access hostnetwork pod via pod ip directly, we cannot do anything i think. Because the original dst ip is a shared node ip.

So what we need to do is supporting the first case. 
currently bpf prog do routing via frontend map -> service map -> endpointmap -> backend map  maps are defined in bpf/kmesh/workload/include/workload.h 

Looks we donot need to update the bpf maps. 

What we should do is updating the userspace workloadCache ops. Preclude storing hotsnetwork pod in `byAddr`

**Comment by hzxuzhonghu** [comment]
Yes,  do you have any place that use getWorkloadbyaddress for hostnetwork pod. Keep in mind, these kind of pods are not managed by kmesh. They are just reachable through kmesh.

**Comment by Okabe-Rintarou-0** [comment]
not used in my code. But in existing codes, we have:

https://github.com/kmesh-net/kmesh/blob/75a73125419cf0b90a027c34a28bd285d8d12aac/pkg/controller/telemetry/metric.go#L169-L198
