### ISSUE TITLE
Add E2E test for Kmesh daemon restart

### ISSUE THREAD

**Issue by YaoZengzeng** [kmesh-net/kmesh#642]
**What would you like to be added**:

1. Test that after Kmesh daemon is successfully restarted, all functions work fine, no need to restart the pods to manage them again.
2. Test that During the restart of Kmesh daemon, connections created by applications in the mesh can be managed normally.
...

This is a complex scenario, continue to add.

**Why is this needed**:

Ensure that Kmesh restart will not effect the normal function of mesh

**Comment by hzxuzhonghu** [comment]
done
