### ISSUE TITLE
Keep the `ghcr.io/kmesh-net/kmesh:latest` image in sync with the master branch

### ISSUE THREAD

**Issue by YaoZengzeng** [kmesh-net/kmesh#644]
**What would you like to be added**:

Use the CI/CD mechanism of Github to update `ghcr.io/kmesh-net/kmesh:latest` once the master branch is updated.

**Why is this needed**:

When developing and testing, we are used to using the latest image of Kmesh. However, we are updating latest image manually from time to time, and we often don't know what the latest commit is in the latest image.

Therefore it's often the case that the function works fine when testing with the latest iamge, but there are problems when merging into the master branch.

If the latest image is synchronized with the latest commit of master branch, this problem can be alleviated to a great extent.

**Comment by hzxuzhonghu** [comment]
It has already do that within github action.  https://github.com/kmesh-net/kmesh/actions/workflows/release-master.yaml

**Comment by YaoZengzeng** [comment]
Excellent!
