### ISSUE TITLE
Does not pewrform when using tcp-echo to test the l4 authorizationPolicy

### ISSUE THREAD

**Issue by LiZhenCheng9527** [kmesh-net/kmesh#653]
**What happened**:
When using tcp-echo to test the l4 authorizationPolicy, it does not perform the relevant actions.

I added the following configuration:
```console
kubectl apply -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: allow-by-tcp-echo 
 namespace: default
spec:
 selector:
   matchLabels:
     app: tcp-echo
 action: ALLOW
 rules:
 - from:
   - source:
       ipBlocks:
       - 10.244.0.118
```

I got:
```console
kubectl exec sleep-bc9998558-w4nf4 -- sh -c 'echo "port 9000" | nc tcp-echo 9000' | grep "hello" && echo 'connection succeeded' || echo 'connection rejected'
hello port 9000
connection succeeded
```
No logs for auth deny.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:  
- Kmesh version: 0.4.0-release
- Others: 5.15.0-102-generic

**Comment by hzxuzhonghu** [comment]
cc @tacslon
