### ISSUE TITLE
TestRemoveAddNsOrServiceWaypoint  flake

### ISSUE THREAD

**Issue by hzxuzhonghu** [kmesh-net/kmesh#704]
https://github.com/kmesh-net/kmesh/actions/runs/10294849725/job/28493564917?pr=679

**Comment by YaoZengzeng** [comment]
It seems like that the Kmesh daemon crashed during the test, casuing the newly deployed waypoint fail to take effect.

**Comment by hzxuzhonghu** [comment]
How do you see kmesh crash from the log?

**Comment by YaoZengzeng** [comment]
> How do you see kmesh crash from the log?

I run e2e tests locally and watch pods in the cluster.

And the default call in e2e test has a retry mechanism, as long as the retry succeeds in 30s, unless you explicitly specifty `NoRetry`.

Therefore, there will be no problem starting the test immediately after add the using waypoint label.

I think this test case will not have flaky issue after #706 is merged. We can continue to observe.
