### ISSUE TITLE
Support build kmesh from container

### ISSUE THREAD

**Issue by hzxuzhonghu** [kmesh-net/kmesh#76]
When I first run build.sh to build kmesh, it installs a lot of dependencies on my VM. While istio has an image named `build-tools`, a developer can run `make build`  `make docker`, `make lint` `make gen`, and many other cmd within the container. It can provide good contributing experience for new contributors.

So let's provide a build tools image, and support build kmesh binary/image from the container.

**Comment by hzxuzhonghu** [comment]
After we run build.sh, some files are mutated and some new files generated, and git tree is not clean. But we should keep it clean after build.

**Comment by weli-l** [comment]
> When I first run build.sh to build kmesh, it installs a lot of dependencies on my VM. While istio has an image named `build-tools`, a developer can run `make build` `make docker`, `make lint` `make gen`, and many other cmd within the container. It can provide good contributing experience for new contributors.
> 
> So let's provide a build tools image, and support build kmesh binary/image from the container.

Could you please provide an explanation for the meaning and intended outcomes of the four commands listed above?

**Comment by hzxuzhonghu** [comment]
`make build` should build the binaries 
`make docker` is used to build docker images.
`make lint` is to do golangci-lint check
`make gen` probably generate the proto and bpf files
