### ISSUE TITLE
kmesh:latest image cannot start

### ISSUE THREAD

**Issue by lec-bit** [kmesh-net/kmesh#767]
**What happened**:
ghcr.io/kmesh-net/kmesh:latest cannot use, I docker pull ghcr.io/kmesh-net/kmesh:latest,and then 
helm install kmesh ./deploy/helm -n kmesh-system
get
```
root@ubuntu-1:/home/zmy/github/kmesh# kubectl get pod -n kmesh-system 
NAME          READY   STATUS             RESTARTS      AGE
kmesh-bmcdt   0/1     CrashLoopBackOff   5 (38s ago)   3m40s
kmesh-gdksv   0/1     CrashLoopBackOff   5 (27s ago)   3m40s
root@ubuntu-1:/home/zmy/github/kmesh# kubectl logs -f -n kmesh-system kmesh-gdksv 
kmesh exit
```
Modify the startup script to ensure that the container is not destroyed. 
Go to the container and check the kmesh-daemon file is empty.
```
root@ubuntu-1:/home/zmy/github/kmesh# kubectl exec -it -n kmesh-system kmesh-w7fzz -- bash


Welcome to 5.15.148

System information as of time: 	Fri Aug 23 08:10:59 UTC 2024

System load: 	0.14
Processes: 	6
Memory used: 	20.8%
Swap used: 	8.3%
Usage On: 	98%
Users online: 	0


[root@kmesh-w7fzz kmesh]# ls
start_kmesh.sh
[root@kmesh-w7fzz kmesh]# cd /usr/bin/
[root@kmesh-w7fzz bin]# ll |grep kmesh
-r-x------ 1 root root       0 Aug 23 03:26 kmesh-cni
-r-x------ 1 root root       0 Aug 23 03:26 kmesh-daemon
[root@kmesh-w7fzz bin]# 

```

kmesh images build ci failed to compile.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kmesh version:
- Others:

**Comment by hzxuzhonghu** [comment]
Is this only on openEuler?

**Comment by lec-bit** [comment]
The openeuler cannot be started, too. The image does not compile the kmesh-daemon.

**Comment by hzxuzhonghu** [comment]
I can reproduce on ubuntu 2204

**Comment by hzxuzhonghu** [comment]
The kmesh-daemon binary size is 0, could be dual  to permission in github action
