### ISSUE TITLE
[E2E Enhancement] support multiple versions of istio

### ISSUE THREAD

**Issue by YaoZengzeng** [kmesh-net/kmesh#782]
**What would you like to be added**:

E2E tests could be run on multiple versions of istio, and some cases only run on specific istio version, such as some newly added features like #697 

**Why is this needed**:

Currently E2E test cases will only run on istio 1.22, but as subsequent istio versions are released and new features are added, we will hope to add new E2E test cases for new features while ensuring compatibilities with older version.

**What needs to be discussed is how many istio versions should we support and how long to retire the oldest version?**

**Comment by hzxuzhonghu** [comment]
That's a resonable feature. For the document, it would be better to add a matrix about kmesh feature and its dependant istio version.

**Comment by LiZhenCheng9527** [comment]
Add a parameter that can select the istio version to run e2e shell scripts?

**Comment by YaoZengzeng** [comment]
> Add a parameter that can select the istio version to run e2e shell scripts?

Yes, actually we already support specifying istio version, ref: https://github.com/kmesh-net/kmesh/blob/main/test/e2e/run_test.sh#L13 , but for new versions, we still need to fully verify the test cases.
