### ISSUE TITLE
Kmesh-daemon version incorrectly return "v0.0.0-master" 

### ISSUE THREAD

**Issue by hzxuzhonghu** [kmesh-net/kmesh#802]
**What happened**:

No matter how we change the VERSION and build docker image , the binary will return something like this 

```
kmesh-daemon version
{
  "gitVersion": "v0.0.0-master",
  "gitCommit": "unknown",
  "gitTreeState": "unknown",
  "buildDate": "unknown",
  "goVersion": "go1.22.5",
  "compiler": "gc",
  "platform": "linux/amd64"
}

```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kmesh version:
- Others:

**Comment by hzxuzhonghu** [comment]
cc @Okabe-Rintarou-0

**Comment by Okabe-Rintarou-0** [comment]
how can we reproduce it ?

**Comment by hzxuzhonghu** [comment]
`kubectl exec kmesh -n kmesh-system -- kmesh-daemon version`
