### ISSUE TITLE
flaky of TestBookinfo

### ISSUE THREAD

**Issue by YaoZengzeng** [kmesh-net/kmesh#829]
**Why is this needed**:

https://github.com/kmesh-net/kmesh/actions/runs/10768178458/job/29856829530?pr=828
https://github.com/kmesh-net/kmesh/actions/runs/10768178465/job/29856829569?pr=828

The image download speed of Github CI may not be as fast and stable as expected. The 60s timeout is not enough which may cause flaky.

**Comment by LiZhenCheng9527** [comment]
Can you extend the timeout or use the `docker pull` and the `kind load docker-image` to load the bookinfo image before running the e2e test?
