### ISSUE TITLE
Improve copyright checker

### ISSUE THREAD

**Issue by hzxuzhonghu** [kmesh-net/kmesh#855]
**Task description**:

We can add a copyright checker to prevent creating files without copyright https://github.com/kmesh-net/kmesh/blob/main/pkg/utils/exec.go#L1-L14

And for .c .h files, https://github.com/kmesh-net/kmesh/blob/main/bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c#L2

**Solution**:

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by yuluo-yx** [comment]
hi @hzxuzhonghu I see that the copyright check ci is already in the code.
https://github.com/yuluo-yx/kmesh/blob/53caaa81015ea23eff89ff41a7be9a7bf0ae115d/.github/workflows/main.yml#L31

**Comment by hzxuzhonghu** [comment]
Yeah. But i kind of remember it did not fail this pr https://github.com/kmesh-net/kmesh/pull/853#discussion_r1759636317

**Comment by yuluo-yx** [comment]
> Yeah. But i kind of remember it did not fail this pr [#853 (comment)](https://github.com/kmesh-net/kmesh/pull/853#discussion_r1759636317)

This script may not be easy to use, I can refactor it using skywalking-eys.

**Comment by hzxuzhonghu** [comment]
IIRC `hack/copyright-check.sh` is missing some dir check

**Comment by hzxuzhonghu** [comment]
cc @yuluo-yx

**Comment by yuluo-yx** [comment]
> cc @yuluo-yx

get, I will try to update.

**Comment by yuluo-yx** [comment]
@hzxuzhonghu I deleted /pkg/controller/workloader/common.go locally and the shell script is fine, it works fine

![image](https://github.com/user-attachments/assets/24ba2480-d67e-41c0-beda-c80bd6bdcab8)

![image](https://github.com/user-attachments/assets/04346be1-b6ba-4fc7-99d6-0b0d7127806f)

maybe we don’t need to update?

**Comment by hzxuzhonghu** [comment]
```
go_dirs="$ROOT_DIR/pkg"
c_dirs="$ROOT_DIR/bpf"
```

From the script, we can see it only checks these two dirs. That;s not enough, we have many other packages

**Comment by yuluo-yx** [comment]
@hzxuzhonghu I've finished this issue, you can close it. 

I am very interested in cloud native and traffic management. If you have other good questions or simple tasks, you can assign them to me and I will try to do them. Thank you very much 🤔

**Comment by LiZhenCheng9527** [comment]
Done
/close
