### ISSUE TITLE
use depguard to prohibitate importing `github.com/golang/protobuf`

### ISSUE THREAD

**Issue by hzxuzhonghu** [kmesh-net/kmesh#868]
**Task description**:

`github.com/golang/protobuf` has been supseded by `google.golang.org/protobuf`, which means almost all the functions are equavaliently implemented there.

But in kmesh we are mixing import anyone of them.  [depguard](https://golangci-lint.run/usage/linters/#depguard) provides a good way to set allowed importing packages. We can make use of it to not allow `github.com/golang/protobuf`

**Solution**:

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by hzxuzhonghu** [comment]
And "gopkg.in/yaml.v3" should be replaced with `sigs.k8s.io/yaml`

**Comment by SpongeBob0318** [comment]
邮件已收到————————————这是来自QQ邮箱的自动回复邮件。

**Comment by hzxuzhonghu** [comment]
Fixed by https://github.com/kmesh-net/kmesh/pull/881
