### ISSUE TITLE
Will kmesh keep waypoint or remove it in the future?

### ISSUE THREAD

**Issue by gczz2022** [kmesh-net/kmesh#872]
I'm new to this project and now reading the docs, i'm wondering do you have a list of features and the place in which the feature is or will be implemented, like in kernel with ebpf or in waypoint. And do you have any plan about whether to keep waypoint or remove it in the future (for example, to implement all the istio things in ebpf)?

Thanks!

**Comment by hzxuzhonghu** [comment]
We will keep  maintaining two patterns: kernel-native(without waypoint) and dual-engine(with waypoint). because of some limitations on ebpf.

For more deatures you can read out website.
