### ISSUE TITLE
Another potential ads deserial bug

### ISSUE THREAD

**Issue by Okabe-Rintarou-0** [kmesh-net/kmesh#875]
**What happened**:
```go
func socketAddressToClang(goMsg *core_v2.SocketAddress) (*C.Core__SocketAddress, error) {
	buf, err := proto.Marshal(goMsg)
	if err != nil {
		return nil, err
	}

	cMsg := C.core__socket_address__unpack(nil, C.size_t(len(buf)), convertToPack(buf))
	if cMsg == nil {
		return nil, fmt.Errorf("core__socket_address__unpack failed")
	}
	return cMsg, nil
}
```

take the above code as example, if the field of goMsg is all zero, proto.Marshal will produce a buf with zero length.
then convertToPack will cause panic.

cc @hzxuzhonghu @nlgwcy 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kmesh version:
- Others:

**Comment by Okabe-Rintarou-0** [comment]
We need special judge for that scenario

**Comment by hzxuzhonghu** [comment]
Will take a look

**Comment by hzxuzhonghu** [comment]
We can return nil when goMsg == nil. And another case: not sure if we should check &SocketAddress{} is empty but not nil. Can you confirm @Okabe-Rintarou-0

**Comment by Okabe-Rintarou-0** [comment]
> We can return nil when goMsg == nil. And another case: not sure if we should check &SocketAddress{} is empty but not nil. Can you confirm @Okabe-Rintarou-0
&SocketAddress{} will be marshal to a nil buf.
but its meaningful, we should give it a length: for example, if max value size is 64, we should make a 64-bytes buf with all zeros.

**Comment by hzxuzhonghu** [comment]
But how could we get the size of it

**Comment by Okabe-Rintarou-0** [comment]
> But how could we get the size of it

bpf map have max value size, we can find a way to get it

**Comment by hzxuzhonghu** [comment]
Looks tricky,  shouldn't  `proto.Marshal(&SocketAddress{})` return `{}`

**Comment by Okabe-Rintarou-0** [comment]
> ketAddress{}

i tried this, proto.Marshal(&SocketAddress{}) will return nil

**Comment by hzxuzhonghu** [comment]
Thanks let me deep dive

**Comment by nlgwcy** [comment]
Will take a look
