### ISSUE TITLE
We should not always trigger CI/CD

### ISSUE THREAD

**Issue by Okabe-Rintarou-0** [kmesh-net/kmesh#880]
**Task description**:
CI/CD like go cicd or e2e test will take lots of time. Sometimes we just modify the docs, it will trigger some meaningless workflows.

I suggest adding path filters for some worklfows: https://github.com/dorny/paths-filter

**Solution**:

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by hzxuzhonghu** [comment]
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore  Github actiopn provide such functionality
