### ISSUE TITLE
can't generate bpf log `subsys=bpf` after setting kmesh-daemon log level.

### ISSUE THREAD

**Issue by derekwin** [kmesh-net/kmesh#883]
```
$ kubectl exec -it kmesh-bk48s -n kmesh-system -- kmesh-daemon log --set bpf:debug
set BPF Log Level: 3

$ kubectl logs -f -n kmesh-system kmesh-bk48s > logs/kmesh.log
^C
$ uname -r
6.4.0-10.1.0.20.oe2309.x86_64

kmesh at commit 56bcc1ff3d4c404274da9bffedefe3c147b01bcf
```

can't generate bpf log with `subsys=bpf` at user space after setting kmesh-daemon log level.

**Comment by hzxuzhonghu** [comment]
@LiZhenCheng9527 ptal

**Comment by LiZhenCheng9527** [comment]
Did you output the log through debug in your code?

**Comment by LiZhenCheng9527** [comment]
I can't reproduce your problem.
My commit is: commit a5dce80724f2b3fe34db4f742e8bac994b80718a

**Comment by LiZhenCheng9527** [comment]
The branch you're on now is a commit from the 12th of September.
Maybe you can fix this by updating the code. 
If you have additional commits on this branch, you can cherry-pick to the new branc.

**Comment by hzxuzhonghu** [comment]
Yes， now @YaoZengzeng added `kmeshctl` to set log level

**Comment by YaoZengzeng** [comment]
@derekwin you could `make build` to get the `kmeshctl` and use `kmeshctl log` command:

```bash
root@dev:~/kmesh# ./kmeshctl log --help
Get or set kmesh-daemon's logger level

Usage:
  kmeshctl log [flags]

Examples:
# Set default logger's level as "debug":
kmeshctl log <kmesh-daemon-pod> --set default:debug

# Get all loggers' name
kmeshctl log <kmesh-daemon-pod>
          
# Get default logger's level:
kmeshctl log <kmesh-daemon-pod> default

Flags:
  -h, --help         help for log
      --set string   Set the logger level (e.g., default:debug)
```

**Comment by derekwin** [comment]
> @derekwin you could `make build` to get the `kmeshctl` and use `kmeshctl log` command:
> 
> ```shell
> root@dev:~/kmesh# ./kmeshctl log --help
> Get or set kmesh-daemon's logger level
> 
> Usage:
>   kmeshctl log [flags]
> 
> Examples:
> # Set default logger's level as "debug":
> kmeshctl log <kmesh-daemon-pod> --set default:debug
> 
> # Get all loggers' name
> kmeshctl log <kmesh-daemon-pod>
>           
> # Get default logger's level:
> kmeshctl log <kmesh-daemon-pod> default
> 
> Flags:
>   -h, --help         help for log
>       --set string   Set the logger level (e.g., default:debug)
> ```

ok, thank you!
And if i have update the document. #904

**Comment by derekwin** [comment]
@hzxuzhonghu @YaoZengzeng
