### ISSUE TITLE
release 0.5.0 preparation

### ISSUE THREAD

**Issue by hzxuzhonghu** [kmesh-net/kmesh#894]
- [x] cut release-v0.5 branch
- [x] update the VERSION to 0.5.0 in Makefile
- [x] package helm chart and push it to ghcr, we need to update the chart version and app version to 0.5.0 before helm package 
- [x] release with a tag v0.5.0 from release-v0.5 branch, than github action will automatically build and push kmesh image
- [x] waypoint image need to build and push manually
- [x] kmeshctl build and release
- [x] release chart package 
- [x] update install document

**Comment by LiZhenCheng9527** [comment]
Done
/close
