### ISSUE TITLE
Add a link about how to use kmesh in read me quick start

### ISSUE THREAD

**Issue by hzxuzhonghu** [kmesh-net/kmesh#93]
**What would you like to be added**:
In quick start here https://github.com/kmesh-net/kmesh/blob/main/README.md#quick-start we do only include contents on how to build image and deploy kmesh, bu IMO we should also add kmesh usage.

**Why is this needed**:

To help users and contributors quickly get started, improve UX

**Comment by LiZhenCheng9527** [comment]
There is already a link to quick-start in the readme
