### ISSUE TITLE
Replace `ads` and `workload` in the code

### ISSUE THREAD

**Issue by LiZhenCheng9527** [kmesh-net/kmesh#937]
**What would you like to be added**:
Replace ads with workload in the code.
**Why is this needed**:
Kmesh advertises that it no longer uses `ads` and `workload`, but uses `duel engine` and `kernel native`, but we still use `ads` and `workload` in our code. should we replace them?

**Comment by hzxuzhonghu** [comment]
We can discuss it in the community meeting
