### ISSUE TITLE
[release 0.4]start_kmesh.sh in 0.4.0 Kmesh arm image doesn't has exec privileges.

### ISSUE THREAD

**Issue by LiZhenCheng9527** [kmesh-net/kmesh#943]
**What happened**:
```sh
/bin/sh: line1: ./start_kmesh.sh: Permission denied
```
**What you expected to happen**:
Give script execution privileges to enable kmesh to start properly
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kmesh version:
- Others:

**Comment by hzxuzhonghu** [comment]
@lec-bit Is this fixed?

**Comment by LiZhenCheng9527** [comment]
@lec-bit

**Comment by LiZhenCheng9527** [comment]
Done
 /close
