### ISSUE TITLE
[release 0.5]Binary in Kmesh arm image not exec properly

### ISSUE THREAD

**Issue by LiZhenCheng9527** [kmesh-net/kmesh#944]
**What happened**:
```sh
./start_kmesh.sh: line 29: /usr/bin/kmesh-daemon: cannot execute binary file: Exec format error
./start_kmesh.sh: line 54: /usr/bin/kmesh-daemon: cannot execute binary file: Exec format error
```
**What you expected to happen**:
Can use Kmesh in an arm architecture OS.
**How to reproduce it (as minimally and precisely as possible)**:
The release 0.5.0 image was built via github action. We may need to validate workflow further.
**Anything else we need to know?**:

**Environment**:
- Kmesh version: 0.5.0
- Others:

**Comment by hzxuzhonghu** [comment]
what os did you run that?

**Comment by LiZhenCheng9527** [comment]
oe2303

**Comment by lec-bit** [comment]
This issue exists in latest, too.
