### ISSUE TITLE
The binary size of `kmeshctl` seems too large

### ISSUE THREAD

**Issue by YaoZengzeng** [kmesh-net/kmesh#946]
**Task description**:

The binary size of `kmeshctl` as follows:

```bash
root@dev:~# ls -lh /usr/local/bin/kmeshctl 
-rwxr-xr-x 1 root root 110M Oct 11 08:11 /usr/local/bin/kmeshctl
```

In contrast, the binary size of `istioctl` is:

```bash
root@dev:~# ls -lh /usr/local/bin/istioctl 
-rwxr-xr-x 1 root root 87M Sep 24 11:54 /usr/local/bin/istioctl
```

size of `kubectl` is:

```bash
root@dev:~# ls -lh /usr/local/bin/kubectl 
-rwxr-xr-x 1 root root 46M Sep 24 07:05 /usr/local/bin/kubectl
```

size of `kmesh-daemon`:

```bash
[root@kmesh-p6cb9 kmesh]# ls -lh /usr/bin/kmesh-daemon 
-r-xr--r-- 1 root root 120M Oct  8 02:59 /usr/bin/kmesh-daemon
```

**Solution**:

Maybe optimize go compilation options or remove unnecessary dependencies?

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by hzxuzhonghu** [comment]
https://github.com/loov/goda And many other similar tools are there

**Comment by am6737** [comment]
Hey @hzxuzhonghu 

I’ve used goda to generate the dependency graph, but I haven’t been able to identify any unnecessary dependencies. It’s possible that I’m not analyzing it correctly. I need your help

[dependency graph](https://github.com/user-attachments/assets/29a46e7f-8f5c-4712-a760-0dffe4822e04)

After adding -s -w to the ldflags, the sizes of the binaries are as follows:
```
ls -lh kmeshctl 
-rwxr-xr-x 1 root root 72M Oct 15 16:49 kmeshctl
```

```
ls -lh out/kmesh-daemon 
-r-xr--r-- 1 root root 87M Oct 15 16:43 out/kmesh-daemon
```

Do you think these sizes are sufficient? Should we consider adding DEBUG flags like all=-N -l, similar to what Kubernetes and Istio do?

kubernetes
```
  if [[ "${DBG:-}" == 1 ]]; then
      # Debugging - disable optimizations and inlining and trimPath
      gogcflags="${gogcflags} all=-N -l"
  else
      # Not debugging - disable symbols and DWARF, trim embedded paths
      goldflags="${goldflags} -s -w"
      goflags+=("-trimpath")
  fi
```

istio
```
ifeq ($(origin DEBUG), undefined)
  BUILDTYPE_DIR:=release
else ifeq ($(DEBUG),0)
  BUILDTYPE_DIR:=release
else
  BUILDTYPE_DIR:=debug
  export GCFLAGS:=all=-N -l
  $(info $(H) Build with debugger information)
endif
```

**Comment by hzxuzhonghu** [comment]
[tree.txt](https://github.com/user-attachments/files/17393131/tree.txt)

This is generated with goda tree, ptal, `istio.io/istio/pkg/kube` seems contains a lot of unneccessary packages. May try to not use it

**Comment by hzxuzhonghu** [comment]
We can construct port-forwarder from k8s.io/kubectl/pkg/cmd/portforward

**Comment by am6737** [comment]
> The graph is based on kmesh-daemon?
> 
> I agree with the suggestion by building with release flag

Sorry for the confusion earlier, I forgot to mention that this dependency graph is actually based on `kmeshctl`.

**Comment by am6737** [comment]
> The graph is based on kmesh-daemon?
> 
> I agree with the suggestion by building with release flag

I apologize for my misunderstanding of how to use Goda. The graph was actually generated by the command `goda graph "./..." | dot -Tsvg -o graph.svg`. I realize that this is incorrect, and I appreciate you pointing that out.

**Comment by am6737** [comment]
> We can construct port-forwarder from k8s.io/kubectl/pkg/cmd/portforward

Thank you for your advice! I really appreciate it, and I will try to write it down.
