### ISSUE TITLE
Provide ways to run integration tests

### ISSUE THREAD

**Issue by VanderChen** [kmesh-net/kmesh#96]
**What would you like to be added**:

A convenient way to run end-to-end tests is needed.

IMO，Reference to [Cilium End-To-End Connectivity Testing](https://docs.cilium.io/en/latest/contributing/testing/e2e/#running-end-to-end-connectivity-tests), a suit of  end-to-end tests with k8s cluster is better for us than re-implemented Mock framework, like Istio.

**Why is this needed**:

**Comment by LiZhenCheng9527** [comment]
kmesh already have e2e test
