### ISSUE TITLE
Fails to start pod with "`GLIBC_2.34' not found"

### ISSUE THREAD

**Issue by Kuromesi** [kmesh-net/kmesh#988]
**Please provide an in-depth description of the question you have**:
When I was trying to run kmesh in my cluster, pods failed to start with errors as below:
```
 Warning  FailedCreatePodSandBox  4m13s (x151 over 37m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "467a1ca2965ffc6f6db2a25e97f7495e257fe721ff5cbf0203f33f7769ffa004": plugin type="kmesh-cni" failed (add): netplugin failed: "/opt/cni/bin/kmesh-cni: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /opt/cni/bin/kmesh-cni)\n"
```

And here is my libc version.
```
[root@iZj6c5j5crox65udl4den7Z ~]# ldd --version
ldd (GNU libc) 2.32
```

Is there any way to compile the kmesh-cni with older libc?

**What do you think about this question?**:

**Environment**:
- Kmesh version: latest
- Others:

**Comment by hzxuzhonghu** [comment]
if we compile kmesh-cni  staticlly, should this not happen?
