### ISSUE TITLE
Update Documentation to Specify Root User Requirement for Kmesh Build Command

### ISSUE THREAD

**Issue by codesmith25103** [kmesh-net/kmesh#992]
**Task description**:
When attempting to build the Kmesh system locally, new users might encounter issues due to the lack of documentation specifying that the build command needs to be run as the root user.

**Solution**:

Update the documentation to inform users that they should execute the build command as the root user to avoid any build-related issues.
**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by codesmith25103** [comment]
I have added new Pull request which will close this issue

**Comment by Okabe-Rintarou-0** [comment]
there will be some file changes after running `make build`, so you can run `make clean` to recover them.

**Comment by codesmith25103** [comment]
ok sure. I will add it update
